# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161231_1859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saller',
            new_name='Seller',
        ),
    ]
